version: '3.9'

services:
  s:
    build:
      context: .
      dockerfile: Dockerfile
#    image: follow
    environment:
      - START_XVFB=false
    shm_size: '2gb'
    volumes:
      - .:/instahelp_web
    command: ["tail", "-f", "/dev/null"]
